window.frequencyWords = [
  { rank: 1, word: "的", pinyin: "de5/di2/di4", pinyinInput: "de di", cz: "částice; přivlastnění / spojení", en: "of / structural particle", frequency: 1682530 },
  { rank: 2, word: "我", pinyin: "wo3", pinyinInput: "wo", cz: "já / mě / můj", en: "I / me / my", frequency: 1682285 },
  { rank: 3, word: "你", pinyin: "ni3", pinyinInput: "ni", cz: "ty", en: "you", frequency: 1329424 },
  { rank: 4, word: "是", pinyin: "shi4", pinyinInput: "shi", cz: "být / jsem / je / ano", en: "is / are / am / yes / to be", frequency: 947807 },
  { rank: 5, word: "了", pinyin: "le5/liao3/liao4", pinyinInput: "le liao", cz: "částice dokončení nebo změny", en: "particle of completion/change", frequency: 946365 },
  { rank: 6, word: "不", pinyin: "bu2/bu4", pinyinInput: "bu", cz: "ne / zápor", en: "not / no", frequency: 689161 },
  { rank: 7, word: "在", pinyin: "zai4", pinyinInput: "zai", cz: "být v / na / nacházet se", en: "at / in / to exist", frequency: 429766 },
  { rank: 8, word: "他", pinyin: "ta1", pinyinInput: "ta", cz: "on / jeho", en: "he / him", frequency: 397653 },
  { rank: 9, word: "我们", pinyin: "wo3 men5", pinyinInput: "wo men", cz: "my / nás / náš", en: "we / us / our", frequency: 371696 },
  { rank: 10, word: "好", pinyin: "hao3/hao4", pinyinInput: "hao", cz: "dobrý / dobře / mít rád", en: "good / well", frequency: 334698 },
  { rank: 11, word: "有", pinyin: "you3/you4", pinyinInput: "you", cz: "mít / existovat", en: "to have / there is", frequency: 289109 },
  { rank: 12, word: "这", pinyin: "zhe4/zhei4", pinyinInput: "zhe zhei", cz: "toto / tito", en: "this / these", frequency: 286987 },
  { rank: 13, word: "就", pinyin: "jiu4", pinyinInput: "jiu", cz: "hned / právě / už / tedy", en: "just / then / already", frequency: 276636 },
  { rank: 14, word: "会", pinyin: "hui4/kuai4", pinyinInput: "hui kuai", cz: "umět / moci / bude / setkat se", en: "can / will / to meet", frequency: 265929 },
  { rank: 15, word: "吗", pinyin: "ma2/ma3/ma5", pinyinInput: "ma", cz: "otázková částice", en: "question particle", frequency: 249187 },
  { rank: 16, word: "要", pinyin: "yao1/yao4", pinyinInput: "yao", cz: "chtít / muset / důležitý", en: "to want / must / important", frequency: 238656 },
  { rank: 17, word: "什么", pinyin: "shen2 me5", pinyinInput: "shen me shenme", cz: "co / něco / cokoli", en: "what / something / anything", frequency: 236517 },
  { rank: 18, word: "说", pinyin: "shui4/shuo1/yue4", pinyinInput: "shui shuo yue", cz: "mluvit / říct", en: "to speak / to say", frequency: 226955 },
  { rank: 19, word: "她", pinyin: "ta1", pinyinInput: "ta", cz: "ona / ji", en: "she", frequency: 221420 },
  { rank: 20, word: "想", pinyin: "xiang3", pinyinInput: "xiang", cz: "myslet / chtít / stýskat se", en: "to think / to want / to miss", frequency: 212185 },
  { rank: 21, word: "一", pinyin: "yi1", pinyinInput: "yi", cz: "jeden / jedno / celý", en: "one / a / whole", frequency: 203626 },
  { rank: 22, word: "很", pinyin: "hen3", pinyinInput: "hen", cz: "velmi / docela", en: "very / quite", frequency: 200584 },
  { rank: 23, word: "知道", pinyin: "zhi1 dao5", pinyinInput: "zhi dao zhidao", cz: "vědět / být si vědom", en: "know / be aware of", frequency: 196745 },
  { rank: 24, word: "人", pinyin: "ren2", pinyinInput: "ren", cz: "člověk / lidé", en: "person / people", frequency: 194914 },
  { rank: 25, word: "吧", pinyin: "ba1/ba5", pinyinInput: "ba", cz: "částice návrhu nebo změkčení", en: "modal particle / suggestion", frequency: 194084 },
  { rank: 26, word: "那", pinyin: "na1/na3/na4/nei4", pinyinInput: "na nei", cz: "tamten / ten / ti", en: "that / those", frequency: 190087 },
  { rank: 27, word: "来", pinyin: "lai2", pinyinInput: "lai", cz: "přijít / přijet", en: "to come", frequency: 185154 },
  { rank: 28, word: "都", pinyin: "dou1/du1", pinyinInput: "dou du", cz: "všichni / všechno / už", en: "all / both", frequency: 177619 },
  { rank: 29, word: "个", pinyin: "ge3/ge4", pinyinInput: "ge", cz: "obecné měrové slovo / klasifikátor", en: "general classifier", frequency: 173905 },
  { rank: 30, word: "能", pinyin: "neng2", pinyinInput: "neng", cz: "moci / být schopný", en: "can / able", frequency: 166656 },
  { rank: 31, word: "去", pinyin: "qu4", pinyinInput: "qu", cz: "jít / jet pryč", en: "to go", frequency: 163054 },
  { rank: 32, word: "没", pinyin: "mei2/mo4", pinyinInput: "mei mo", cz: "nemít / zápor pro minulost", en: "have not / not", frequency: 159508 },
  { rank: 33, word: "和", pinyin: "he2/he4/hu2/huo2/huo4", pinyinInput: "he hu huo", cz: "a / s / harmonie", en: "and / with / harmony", frequency: 150418 },
  { rank: 34, word: "他们", pinyin: "ta1 men5", pinyinInput: "ta men tamen", cz: "oni / je", en: "they", frequency: 140460 },
  { rank: 35, word: "到", pinyin: "dao4", pinyinInput: "dao", cz: "dorazit / do / až do", en: "to arrive / until", frequency: 139534 },
  { rank: 36, word: "对", pinyin: "dui4", pinyinInput: "dui", cz: "správný / vůči / naproti", en: "correct / opposite / toward", frequency: 132805 },
  { rank: 37, word: "也", pinyin: "ye3", pinyinInput: "ye", cz: "také / taky", en: "also / too", frequency: 131801 },
  { rank: 38, word: "啊", pinyin: "a1/a2/a3/a4/a5", pinyinInput: "a", cz: "citoslovce / větná částice", en: "interjection / modal particle", frequency: 130963 },
  { rank: 39, word: "还", pinyin: "hai2/huan2", pinyinInput: "hai huan", cz: "ještě / také / vrátit", en: "still / also / return", frequency: 130326 },
  { rank: 40, word: "把", pinyin: "ba3/ba4", pinyinInput: "ba", cz: "držet / držadlo / částice 把", en: "hold / handle / ba-particle", frequency: 124534 },
  { rank: 41, word: "让", pinyin: "rang4", pinyinInput: "rang", cz: "nechat / dovolit", en: "to let / to allow", frequency: 123809 },
  { rank: 42, word: "做", pinyin: "zuo4", pinyinInput: "zuo", cz: "dělat / vytvořit", en: "to do / to make", frequency: 122364 },
  { rank: 43, word: "给", pinyin: "gei3/ji3", pinyinInput: "gei ji", cz: "dát / pro / někomu", en: "to give / for", frequency: 117218 },
  { rank: 44, word: "一个", pinyin: "yi1 ge4", pinyinInput: "yi ge yige", cz: "jeden / nějaký", en: "a / an", frequency: 116726 },
  { rank: 45, word: "上", pinyin: "shang3/shang4", pinyinInput: "shang", cz: "nahoře / na / předchozí", en: "on / above / previous", frequency: 114371 },
  { rank: 46, word: "你们", pinyin: "ni3 men5", pinyinInput: "ni men nimen", cz: "vy", en: "you plural", frequency: 112946 },
  { rank: 47, word: "过", pinyin: "guo1/guo4", pinyinInput: "guo", cz: "projít / zkušenostní částice", en: "experienced action marker / to pass", frequency: 112388 },
  { rank: 48, word: "没有", pinyin: "mei2 you3", pinyinInput: "mei you meiyou", cz: "nemít / není / neexistuje", en: "not have / there is not", frequency: 108237 },
  { rank: 49, word: "得", pinyin: "de2/de5/dei3", pinyinInput: "de dei", cz: "částice způsobu / muset / získat", en: "structural particle / must / obtain", frequency: 105189 },
  { rank: 50, word: "看", pinyin: "kan1/kan4", pinyinInput: "kan", cz: "dívat se / vidět / číst", en: "to see / to look / to read", frequency: 102546 },
  { rank: 51, word: "真", pinyin: "zhen1", pinyinInput: "zhen", cz: "opravdu / pravý", en: "really / true", frequency: 102445 },
  { rank: 52, word: "着", pinyin: "zhao1/zhao2/zhe5/zhuo2", pinyinInput: "zhao zhe zhuo", cz: "částice průběhu / dotknout se / nosit", en: "progressive particle / touch / wear", frequency: 100091 },
  { rank: 53, word: "事", pinyin: "shi4", pinyinInput: "shi", cz: "věc / záležitost", en: "matter / thing / affair", frequency: 97715 },
  { rank: 54, word: "这个", pinyin: "zhe4 ge5", pinyinInput: "zhe ge zhege", cz: "tento / tahle věc", en: "this / this one", frequency: 92058 },
  { rank: 55, word: "怎么", pinyin: "zen3 me5", pinyinInput: "zen me zenme", cz: "jak / proč", en: "how / why", frequency: 89166 },
  { rank: 56, word: "现在", pinyin: "xian4 zai4", pinyinInput: "xian zai xianzai", cz: "teď / v současnosti", en: "now / at present", frequency: 88120 },
  { rank: 57, word: "可以", pinyin: "ke3 yi3", pinyinInput: "ke yi keyi", cz: "moci / smět / dá se", en: "can / may / possible", frequency: 79198 },
  { rank: 58, word: "点", pinyin: "dian3", pinyinInput: "dian", cz: "bod / trochu / hodina", en: "point / dot / a little / o'clock", frequency: 77665 },
  { rank: 59, word: "呢", pinyin: "na4/ne4/ne5/ni2", pinyinInput: "na ne ni", cz: "částice tématu nebo otázky", en: "topic/question particle", frequency: 76752 },
  { rank: 60, word: "如果", pinyin: "ru2 guo3", pinyinInput: "ru guo ruguo", cz: "pokud / jestliže", en: "if", frequency: 76417 },
  { rank: 61, word: "只", pinyin: "zhi1/zhi3", pinyinInput: "zhi", cz: "jen / pouze / měrové slovo", en: "only / classifier", frequency: 72698 },
  { rank: 62, word: "别", pinyin: "bie2/bie4", pinyinInput: "bie", cz: "nedělej / jiný / oddělit", en: "do not / other / separate", frequency: 69865 },
  { rank: 63, word: "哦", pinyin: "e2/o2/o4/wo2/wo4", pinyinInput: "e o wo", cz: "aha / ó", en: "oh", frequency: 69380 },
  { rank: 64, word: "但", pinyin: "dan4", pinyinInput: "dan", cz: "ale / avšak", en: "but / however", frequency: 68241 },
  { rank: 65, word: "被", pinyin: "bei4", pinyinInput: "bei", cz: "pasivní částice / být něčím zasažen", en: "passive marker / by", frequency: 65695 },
  { rank: 66, word: "走", pinyin: "zou3", pinyinInput: "zou", cz: "jít / odejít", en: "to walk / to leave", frequency: 65258 },
  { rank: 67, word: "太", pinyin: "tai4", pinyinInput: "tai", cz: "příliš / velmi", en: "too / very", frequency: 65151 },
  { rank: 68, word: "这样", pinyin: "zhe4 yang4", pinyinInput: "zhe yang zheyang", cz: "takto / takový", en: "like this / this way", frequency: 64295 },
  { rank: 69, word: "里", pinyin: "li3", pinyinInput: "li", cz: "uvnitř / v", en: "inside / interior", frequency: 63276 },
  { rank: 70, word: "跟", pinyin: "gen1", pinyinInput: "gen", cz: "s / a / následovat", en: "with / and / follow", frequency: 62979 },
  { rank: 71, word: "告诉", pinyin: "gao4 su5", pinyinInput: "gao su gaosu", cz: "říct / informovat", en: "to tell", frequency: 61222 },
  { rank: 72, word: "因为", pinyin: "yin1 wei4", pinyinInput: "yin wei yinwei", cz: "protože", en: "because", frequency: 59823 },
  { rank: 73, word: "自己", pinyin: "zi4 ji3", pinyinInput: "zi ji ziji", cz: "sám / vlastní", en: "self / own", frequency: 57978 },
  { rank: 74, word: "再", pinyin: "zai4", pinyinInput: "zai", cz: "znovu / potom", en: "again / then", frequency: 56520 },
  { rank: 75, word: "听", pinyin: "ting1", pinyinInput: "ting", cz: "poslouchat / slyšet", en: "to listen / to hear", frequency: 54888 },
  { rank: 76, word: "这里", pinyin: "zhe4 li3", pinyinInput: "zhe li zheli", cz: "tady / zde", en: "here", frequency: 53900 },
  { rank: 77, word: "快", pinyin: "kuai4", pinyinInput: "kuai", cz: "rychlý / brzy", en: "fast / soon", frequency: 53510 },
  { rank: 78, word: "谁", pinyin: "shei2/shui2", pinyinInput: "shei shui", cz: "kdo", en: "who", frequency: 52782 },
  { rank: 79, word: "但是", pinyin: "dan4 shi4", pinyinInput: "dan shi danshi", cz: "ale / avšak", en: "but / however", frequency: 52718 },
  { rank: 80, word: "多", pinyin: "duo1", pinyinInput: "duo", cz: "mnoho / hodně", en: "many / much", frequency: 52605 },
  { rank: 81, word: "用", pinyin: "yong4", pinyinInput: "yong", cz: "používat", en: "to use", frequency: 52436 },
  { rank: 82, word: "时候", pinyin: "shi2 hou5", pinyinInput: "shi hou shihou", cz: "čas / chvíle", en: "time / moment", frequency: 52176 },
  { rank: 83, word: "下", pinyin: "xia4", pinyinInput: "xia", cz: "dole / pod / příští", en: "down / below / next", frequency: 51975 },
  { rank: 84, word: "已经", pinyin: "yi3 jing1", pinyinInput: "yi jing yijing", cz: "už", en: "already", frequency: 51772 },
  { rank: 85, word: "谢谢", pinyin: "xie4 xie5", pinyinInput: "xie xiexie", cz: "děkuji / děkovat", en: "thanks / to thank", frequency: 51457 },
  { rank: 86, word: "为什么", pinyin: "wei4 shen2 me5", pinyinInput: "wei shen me weishenme", cz: "proč / z jakého důvodu", en: "why", frequency: 51063 },
  { rank: 87, word: "觉得", pinyin: "jue2 de5", pinyinInput: "jue de juede", cz: "myslet si / cítit", en: "to think / to feel", frequency: 51047 },
  { rank: 88, word: "天", pinyin: "tian1", pinyinInput: "tian", cz: "den / nebe", en: "day / sky", frequency: 50660 },
  { rank: 89, word: "像", pinyin: "xiang4", pinyinInput: "xiang", cz: "podobat se / jako", en: "like / resemble", frequency: 50229 },
  { rank: 90, word: "这么", pinyin: "zhe4 me5", pinyinInput: "zhe me zheme", cz: "tak / tolik / takhle", en: "so / this much", frequency: 49082 },
  { rank: 91, word: "它", pinyin: "ta1", pinyinInput: "ta", cz: "ono / to", en: "it", frequency: 49024 },
  { rank: 92, word: "从", pinyin: "cong1/cong2", pinyinInput: "cong", cz: "od / z / následovat", en: "from / through / follow", frequency: 47313 },
  { rank: 93, word: "先生", pinyin: "xian1 sheng5", pinyinInput: "xian sheng xiansheng", cz: "pan / učitel / gentleman", en: "sir / mister / teacher", frequency: 46864 },
  { rank: 94, word: "找", pinyin: "zhao3", pinyinInput: "zhao", cz: "hledat", en: "to look for", frequency: 46647 },
  { rank: 95, word: "最", pinyin: "zui4", pinyinInput: "zui", cz: "nejvíc / nej-", en: "most", frequency: 46464 },
  { rank: 96, word: "喜欢", pinyin: "xi3 huan5", pinyinInput: "xi huan xihuan", cz: "mít rád / líbit se", en: "to like", frequency: 46146 },
  { rank: 97, word: "可", pinyin: "ke3/ke4", pinyinInput: "ke", cz: "moci / smět / opravdu", en: "can / may / permit", frequency: 46123 },
  { rank: 98, word: "为", pinyin: "wei2/wei4", pinyinInput: "wei", cz: "jako / pro / kvůli", en: "as / for / because of", frequency: 45565 },
  { rank: 99, word: "大", pinyin: "da4/dai4", pinyinInput: "da dai", cz: "velký / hlavní", en: "big / large", frequency: 45061 },
  { rank: 100, word: "可能", pinyin: "ke3 neng2", pinyinInput: "ke neng keneng", cz: "možná / možný", en: "possible / maybe", frequency: 44424 }
];

const usageData = {
  "的": ["Částice 的 spojuje přivlastnění nebo popis s podstatným jménem.", ["这是我的书。|Zhe4 shi4 wo3 de shu1.|To je moje kniha.|This is my book.", "红色的车在外面。|Hong2se4 de che1 zai4 wai4mian.|Červené auto je venku.|The red car is outside.", "她的中文很好。|Ta1 de Zhong1wen2 hen3 hao3.|Její čínština je velmi dobrá.|Her Chinese is very good."]],
  "我": ["我 znamená já a označuje člověka, který mluví.", ["我是学生。|Wo3 shi4 xue2sheng.|Jsem student.|I am a student.", "我在家。|Wo3 zai4 jia1.|Jsem doma.|I am at home.", "我喜欢中文。|Wo3 xi3huan5 Zhong1wen2.|Mám rád/a čínštinu.|I like Chinese."]],
  "你": ["你 znamená ty a používá se při oslovení jedné osoby.", ["你好吗？|Ni3 hao3 ma5?|Jak se máš?|How are you?", "你有时间吗？|Ni3 you3 shi2jian1 ma5?|Máš čas?|Do you have time?", "你在这里等我。|Ni3 zai4 zhe4li3 deng3 wo3.|Počkej tady na mě.|Wait for me here."]],
  "是": ["是 je základní sloveso být pro určení nebo identitu.", ["这是我的书。|Zhe4 shi4 wo3 de shu1.|To je moje kniha.|This is my book.", "他是老师。|Ta1 shi4 lao3shi1.|On je učitel.|He is a teacher.", "今天是星期一。|Jin1tian1 shi4 xing1qi1yi1.|Dnes je pondělí.|Today is Monday."]],
  "了": ["了 často ukazuje změnu stavu nebo dokončení děje.", ["我吃了。|Wo3 chi1 le5.|Už jsem jedl/a.|I have eaten.", "天黑了。|Tian1 hei1 le5.|Setmělo se.|It has become dark.", "他走了。|Ta1 zou3 le5.|Odešel.|He left."]],
  "不": ["不 tvoří běžný zápor před slovesem nebo přídavným výrazem.", ["我不去。|Wo3 bu2 qu4.|Nepůjdu.|I am not going.", "这不对。|Zhe4 bu2 dui4.|To není správně.|This is not right.", "我不喜欢这个。|Wo3 bu4 xi3huan5 zhe4ge5.|Tohle nemám rád/a.|I do not like this."]],
  "在": ["在 vyjadřuje místo nebo probíhající děj.", ["我在家。|Wo3 zai4 jia1.|Jsem doma.|I am at home.", "书在桌子上。|Shu1 zai4 zhuo1zi5 shang4.|Kniha je na stole.|The book is on the table.", "他在看书。|Ta1 zai4 kan4 shu1.|Čte knihu.|He is reading a book."]],
  "他": ["他 znamená on nebo jeho.", ["他是我朋友。|Ta1 shi4 wo3 peng2you5.|On je můj kamarád.|He is my friend.", "他在工作。|Ta1 zai4 gong1zuo4.|On pracuje.|He is working.", "我告诉他。|Wo3 gao4su5 ta1.|Řeknu mu to.|I tell him."]],
  "我们": ["我们 znamená my a používá se pro skupinu včetně mluvčího.", ["我们走吧。|Wo3men5 zou3 ba5.|Pojďme.|Let's go.", "我们在这里。|Wo3men5 zai4 zhe4li3.|Jsme tady.|We are here.", "我们今天学习中文。|Wo3men5 jin1tian1 xue2xi2 Zhong1wen2.|Dnes se učíme čínsky.|Today we study Chinese."]],
  "好": ["好 znamená dobrý, dobře nebo hotovo podle kontextu.", ["这个很好。|Zhe4ge5 hen3 hao3.|Tohle je velmi dobré.|This is very good.", "你好！|Ni3 hao3!|Ahoj!|Hello!", "饭做好了。|Fan4 zuo4 hao3 le5.|Jídlo je hotové.|The food is ready."]],
  "有": ["有 znamená mít nebo existovat.", ["我有水。|Wo3 you3 shui3.|Mám vodu.|I have water.", "这里有人。|Zhe4li3 you3 ren2.|Tady je člověk.|There is someone here.", "你有问题吗？|Ni3 you3 wen4ti2 ma5?|Máš otázku?|Do you have a question?"]],
  "这": ["这 ukazuje na něco blízkého: toto, tenhle.", ["这是什么？|Zhe4 shi4 shen2me5?|Co je tohle?|What is this?", "这很好吃。|Zhe4 hen3 hao3chi1.|Tohle je moc dobré k jídlu.|This tastes good.", "这不是我的。|Zhe4 bu2 shi4 wo3 de5.|Tohle není moje.|This is not mine."]],
  "就": ["就 často znamená právě, hned, už nebo pak podle věty.", ["我马上就来。|Wo3 ma3shang4 jiu4 lai2.|Hned přijdu.|I will come right away.", "他就在这里。|Ta1 jiu4 zai4 zhe4li3.|Je přímo tady.|He is right here.", "你说，我就听。|Ni3 shuo1, wo3 jiu4 ting1.|Když mluvíš, poslouchám.|If you speak, I listen."]],
  "会": ["会 znamená umět, moci nebo budoucí děj podle kontextu.", ["我会说一点中文。|Wo3 hui4 shuo1 yi4 dian3 Zhong1wen2.|Umím mluvit trochu čínsky.|I can speak a little Chinese.", "明天会下雨。|Ming2tian1 hui4 xia4 yu3.|Zítra bude pršet.|It will rain tomorrow.", "我们会再见。|Wo3men5 hui4 zai4 jian4.|Zase se uvidíme.|We will meet again."]],
  "吗": ["吗 mění oznamovací větu na otázku ano/ne.", ["你好吗？|Ni3 hao3 ma5?|Jak se máš?|How are you?", "你去吗？|Ni3 qu4 ma5?|Půjdeš?|Are you going?", "这是你的书吗？|Zhe4 shi4 ni3 de5 shu1 ma5?|Je to tvoje kniha?|Is this your book?"]],
  "要": ["要 znamená chtít, potřebovat nebo blízký budoucí děj.", ["我要水。|Wo3 yao4 shui3.|Chci vodu.|I want water.", "我要走了。|Wo3 yao4 zou3 le5.|Už musím jít.|I have to go now.", "你要什么？|Ni3 yao4 shen2me5?|Co chceš?|What do you want?"]],
  "什么": ["什么 znamená co, něco nebo jaký podle kontextu.", ["你吃什么？|Ni3 chi1 shen2me5?|Co jíš?|What are you eating?", "这是什么？|Zhe4 shi4 shen2me5?|Co je to?|What is this?", "我什么都不知道。|Wo3 shen2me5 dou1 bu4 zhi1dao5.|Nic nevím.|I don't know anything."]],
  "说": ["说 znamená mluvit nebo říct.", ["你说什么？|Ni3 shuo1 shen2me5?|Co říkáš?|What are you saying?", "他说中文。|Ta1 shuo1 Zhong1wen2.|Mluví čínsky.|He speaks Chinese.", "请慢慢说。|Qing3 man4man5 shuo1.|Mluvte prosím pomalu.|Please speak slowly."]],
  "她": ["她 znamená ona nebo ji.", ["她是医生。|Ta1 shi4 yi1sheng1.|Ona je lékařka.|She is a doctor.", "她在家。|Ta1 zai4 jia1.|Ona je doma.|She is at home.", "我认识她。|Wo3 ren4shi5 ta1.|Znám ji.|I know her."]],
  "想": ["想 znamená myslet, chtít nebo stýskat se.", ["我想喝水。|Wo3 xiang3 he1 shui3.|Chci pít vodu.|I want to drink water.", "你想去哪里？|Ni3 xiang3 qu4 na3li3?|Kam chceš jít?|Where do you want to go?", "我想家。|Wo3 xiang3 jia1.|Stýská se mi po domově.|I miss home."]],
  "一": ["一 znamená jeden a často stojí před měrovým slovem.", ["我有一本书。|Wo3 you3 yi4 ben3 shu1.|Mám jednu knihu.|I have one book.", "一天很快过去。|Yi4 tian1 hen3 kuai4 guo4qu4.|Jeden den rychle uběhne.|One day passes quickly.", "请等一下。|Qing3 deng3 yi2 xia4.|Počkejte prosím chvilku.|Please wait a moment."]],
  "很": ["很 je běžné příslovce stupně: velmi, docela.", ["她很好。|Ta1 hen3 hao3.|Má se dobře.|She is fine.", "今天很热。|Jin1tian1 hen3 re4.|Dnes je velmi horko.|It is very hot today.", "这个人很好。|Zhe4ge5 ren2 hen3 hao3.|Ten člověk je velmi hodný.|This person is very nice."]],
  "知道": ["知道 znamená vědět nebo znát informaci.", ["我知道。|Wo3 zhi1dao5.|Vím.|I know.", "你知道吗？|Ni3 zhi1dao5 ma5?|Víš to?|Do you know?", "我不知道他的名字。|Wo3 bu4 zhi1dao5 ta1 de5 ming2zi5.|Neznám jeho jméno.|I don't know his name."]],
  "人": ["人 znamená člověk nebo lidé.", ["这里有人。|Zhe4li3 you3 ren2.|Tady někdo je.|There is someone here.", "他是好人。|Ta1 shi4 hao3 ren2.|Je to dobrý člověk.|He is a good person.", "很多人喜欢这里。|Hen3 duo1 ren2 xi3huan5 zhe4li3.|Mnoho lidí to tady má rádo.|Many people like it here."]],
  "吧": ["吧 změkčuje návrh, výzvu nebo odhad.", ["走吧。|Zou3 ba5.|Pojďme.|Let's go.", "你休息一下吧。|Ni3 xiu1xi5 yi2 xia4 ba5.|Odpočiň si trochu.|Take a little rest.", "他应该在家吧。|Ta1 ying1gai1 zai4 jia1 ba5.|Asi je doma.|He is probably at home."]],
  "那": ["那 ukazuje na něco vzdálenějšího: ten, tamten.", ["那是什么？|Na4 shi4 shen2me5?|Co je tamto?|What is that?", "那个人是谁？|Na4ge5 ren2 shi4 shei2?|Kdo je ten člověk?|Who is that person?", "那我先走了。|Na4 wo3 xian1 zou3 le5.|Tak já nejdřív půjdu.|Then I'll go first."]],
  "来": ["来 znamená přijít nebo přijet směrem k mluvčímu.", ["请来这里。|Qing3 lai2 zhe4li3.|Pojďte prosím sem.|Please come here.", "他明天来。|Ta1 ming2tian1 lai2.|Přijde zítra.|He will come tomorrow.", "我马上来。|Wo3 ma3shang4 lai2.|Hned přijdu.|I am coming right away."]],
  "都": ["都 znamená všichni, všechno nebo zdůrazňuje celek.", ["我们都去。|Wo3men5 dou1 qu4.|Jdeme všichni.|We are all going.", "他们都知道。|Ta1men5 dou1 zhi1dao5.|Oni to všichni vědí.|They all know.", "这里的东西都很好。|Zhe4li3 de5 dong1xi5 dou1 hen3 hao3.|Věci tady jsou všechny dobré.|Everything here is good."]],
  "个": ["个 je nejběžnější měrové slovo mezi číslem a podstatným jménem.", ["一个人。|Yi2 ge5 ren2.|Jeden člověk.|One person.", "三个苹果。|San1 ge5 ping2guo3.|Tři jablka.|Three apples.", "这个人很好。|Zhe4 ge5 ren2 hen3 hao3.|Tenhle člověk je hodný.|This person is nice."]],
  "能": ["能 znamená moci nebo být schopný něco udělat.", ["我能帮你。|Wo3 neng2 bang1 ni3.|Můžu ti pomoct.|I can help you.", "你能来吗？|Ni3 neng2 lai2 ma5?|Můžeš přijít?|Can you come?", "今天不能去。|Jin1tian1 bu4 neng2 qu4.|Dnes nemůžu jít.|I can't go today."]],
  "去": ["去 znamená jít nebo jet někam pryč od mluvčího.", ["我去学校。|Wo3 qu4 xue2xiao4.|Jdu do školy.|I go to school.", "你去哪儿？|Ni3 qu4 nar3?|Kam jdeš?|Where are you going?", "我们明天去。|Wo3men5 ming2tian1 qu4.|Půjdeme zítra.|We will go tomorrow."]],
  "没": ["没 je zápor pro mít/neexistovat a často pro minulý děj.", ["我没钱。|Wo3 mei2 qian2.|Nemám peníze.|I don't have money.", "他没来。|Ta1 mei2 lai2.|Nepřišel.|He did not come.", "这里没人。|Zhe4li3 mei2 ren2.|Tady nikdo není.|There is nobody here."]],
  "和": ["和 znamená a nebo s.", ["我和你一起去。|Wo3 he2 ni3 yi4qi3 qu4.|Půjdu s tebou.|I will go with you.", "茶和水都可以。|Cha2 he2 shui3 dou1 ke3yi3.|Čaj i voda jsou v pořádku.|Tea and water are both fine.", "他和朋友说话。|Ta1 he2 peng2you5 shuo1hua4.|Mluví s kamarádem.|He talks with a friend."]],
  "他们": ["他们 znamená oni nebo je.", ["他们在外面。|Ta1men5 zai4 wai4mian5.|Oni jsou venku.|They are outside.", "我认识他们。|Wo3 ren4shi5 ta1men5.|Znám je.|I know them.", "他们都来了。|Ta1men5 dou1 lai2 le5.|Všichni přišli.|They all came."]],
  "到": ["到 vyjadřuje dorazit, dostat se někam nebo až do určité doby.", ["我到了。|Wo3 dao4 le5.|Dorazil/a jsem.|I have arrived.", "他到家了。|Ta1 dao4 jia1 le5.|Dorazil domů.|He arrived home.", "我们走到学校。|Wo3men5 zou3 dao4 xue2xiao4.|Dojdeme pěšky do školy.|We walk to school."]],
  "对": ["对 znamená správný, vůči nebo k někomu/něčemu.", ["这个答案对。|Zhe4ge5 da2'an4 dui4.|Tato odpověď je správná.|This answer is correct.", "我对中文感兴趣。|Wo3 dui4 Zhong1wen2 gan3 xing4qu4.|Zajímám se o čínštinu.|I am interested in Chinese.", "你说得对。|Ni3 shuo1 de5 dui4.|Máš pravdu.|What you said is right."]],
  "也": ["也 znamená také nebo taky.", ["我也去。|Wo3 ye3 qu4.|Jdu taky.|I am going too.", "他也会说中文。|Ta1 ye3 hui4 shuo1 Zhong1wen2.|On také umí čínsky.|He can also speak Chinese.", "这里也很好。|Zhe4li3 ye3 hen3 hao3.|Tady je to taky dobré.|It is also good here."]],
  "啊": ["啊 je citoslovce nebo částice, která dává větě přirozenější tón.", ["你好啊！|Ni3 hao3 a5!|Ahoj!|Hello!", "原来是这样啊。|Yuan2lai2 shi4 zhe4yang4 a5.|Aha, takhle to je.|Oh, so that's how it is.", "你来啊！|Ni3 lai2 a5!|Tak pojď!|Come on!"]],
  "还": ["还 znamená ještě, stále nebo také.", ["我还在家。|Wo3 hai2 zai4 jia1.|Ještě jsem doma.|I am still at home.", "你还要水吗？|Ni3 hai2 yao4 shui3 ma5?|Chceš ještě vodu?|Do you still want water?", "他还会说英语。|Ta1 hai2 hui4 shuo1 Ying1yu3.|Umí také anglicky.|He also can speak English."]],
  "把": ["把 přesouvá předmět před sloveso, často když s ním něco uděláme.", ["请把门打开。|Qing3 ba3 men2 da3kai1.|Otevřete prosím dveře.|Please open the door.", "我把书放在桌子上。|Wo3 ba3 shu1 fang4 zai4 zhuo1zi5 shang4.|Položil/a jsem knihu na stůl.|I put the book on the table.", "他把水喝了。|Ta1 ba3 shui3 he1 le5.|Vypil vodu.|He drank the water."]],
  "让": ["让 znamená nechat, dovolit nebo způsobit, aby někdo něco udělal.", ["让我看看。|Rang4 wo3 kan4kan5.|Nech mě se podívat.|Let me have a look.", "老师让我们读书。|Lao3shi1 rang4 wo3men5 du2 shu1.|Učitel nás nechal číst.|The teacher asked us to read.", "这件事让我很高兴。|Zhe4 jian4 shi4 rang4 wo3 hen3 gao1xing4.|Tahle věc mě potěšila.|This made me happy."]],
  "做": ["做 znamená dělat, vyrábět nebo pracovat jako něco.", ["你在做什么？|Ni3 zai4 zuo4 shen2me5?|Co děláš?|What are you doing?", "我做饭。|Wo3 zuo4 fan4.|Vařím.|I cook.", "他做得很好。|Ta1 zuo4 de5 hen3 hao3.|Udělala to velmi dobře.|He did it very well."]],
  "给": ["给 znamená dát, někomu/pro někoho nebo se používá v pasivním smyslu.", ["我给你水。|Wo3 gei3 ni3 shui3.|Dám ti vodu.|I give you water.", "请给我一个。|Qing3 gei3 wo3 yi2 ge5.|Dejte mi prosím jeden.|Please give me one.", "他给朋友打电话。|Ta1 gei3 peng2you5 da3 dian4hua4.|Volá kamarádovi.|He calls a friend."]],
  "一个": ["一个 znamená jeden kus nebo neurčité 'nějaký'.", ["我有一个问题。|Wo3 you3 yi2 ge5 wen4ti2.|Mám jednu otázku.|I have one question.", "这里有一个人。|Zhe4li3 you3 yi2 ge5 ren2.|Tady je jeden člověk.|There is one person here.", "我想要一个。|Wo3 xiang3 yao4 yi2 ge5.|Chci jeden.|I want one."]],
  "上": ["上 znamená nahoře, na, jít nahoru nebo předchozí podle kontextu.", ["书在桌子上。|Shu1 zai4 zhuo1zi5 shang4.|Kniha je na stole.|The book is on the table.", "我上车了。|Wo3 shang4 che1 le5.|Nastoupil/a jsem do auta.|I got into the car.", "上个星期很忙。|Shang4 ge5 xing1qi1 hen3 mang2.|Minulý týden byl rušný.|Last week was busy."]],
  "你们": ["你们 znamená vy, tedy více oslovených lidí.", ["你们好吗？|Ni3men5 hao3 ma5?|Jak se máte?|How are you all?", "你们一起去吗？|Ni3men5 yi4qi3 qu4 ma5?|Půjdete spolu?|Are you going together?", "我等你们。|Wo3 deng3 ni3men5.|Počkám na vás.|I will wait for you."]],
  "过": ["过 může znamenat projít, strávit čas nebo zkušenostní částici.", ["我去过中国。|Wo3 qu4 guo4 Zhong1guo2.|Byl/a jsem v Číně.|I have been to China.", "时间过得很快。|Shi2jian1 guo4 de5 hen3 kuai4.|Čas utíká rychle.|Time passes quickly.", "我们过马路。|Wo3men5 guo4 ma3lu4.|Přecházíme silnici.|We cross the road."]],
  "没有": ["没有 znamená nemít nebo že něco neexistuje.", ["我没有钱。|Wo3 mei2you3 qian2.|Nemám peníze.|I don't have money.", "这里没有人。|Zhe4li3 mei2you3 ren2.|Tady nikdo není.|There is nobody here.", "他今天没有来。|Ta1 jin1tian1 mei2you3 lai2.|Dnes nepřišel.|He did not come today."]],
  "得": ["得 po slovese popisuje, jak děj probíhá; jinde může znamenat muset.", ["他说得很好。|Ta1 shuo1 de5 hen3 hao3.|Mluví velmi dobře.|He speaks very well.", "我跑得不快。|Wo3 pao3 de5 bu2 kuai4.|Neběhám rychle.|I don't run fast.", "我得走了。|Wo3 dei3 zou3 le5.|Musím jít.|I have to go."]],
  "看": ["看 znamená dívat se, vidět, číst nebo sledovat.", ["我看书。|Wo3 kan4 shu1.|Čtu knihu.|I read a book.", "你看这里。|Ni3 kan4 zhe4li3.|Podívej se sem.|Look here.", "我们看电影。|Wo3men5 kan4 dian4ying3.|Díváme se na film.|We watch a movie."]],
  "真": ["真 znamená opravdu nebo pravý.", ["你真好。|Ni3 zhen1 hao3.|Jsi opravdu hodný/á.|You are really nice.", "这是真的吗？|Zhe4 shi4 zhen1 de5 ma5?|Je to pravda?|Is this true?", "今天真热。|Jin1tian1 zhen1 re4.|Dnes je opravdu horko.|It is really hot today."]],
  "着": ["着 po slovese často ukazuje trvající stav nebo děj.", ["门开着。|Men2 kai1 zhe5.|Dveře jsou otevřené.|The door is open.", "他坐着看书。|Ta1 zuo4 zhe5 kan4 shu1.|Sedí a čte.|He is sitting and reading.", "灯亮着。|Deng1 liang4 zhe5.|Světlo svítí.|The light is on."]],
  "事": ["事 znamená věc, záležitost nebo událost.", ["我有事。|Wo3 you3 shi4.|Mám něco na práci.|I have something to do.", "这件事很重要。|Zhe4 jian4 shi4 hen3 zhong4yao4.|Tahle věc je důležitá.|This matter is important.", "没事。|Mei2 shi4.|To nic.|It's okay."]],
  "这个": ["这个 znamená tento, tahle věc nebo tento kus.", ["这个很好。|Zhe4ge5 hen3 hao3.|Tohle je dobré.|This is good.", "我要这个。|Wo3 yao4 zhe4ge5.|Chci tohle.|I want this one.", "这个人是谁？|Zhe4ge5 ren2 shi4 shei2?|Kdo je tenhle člověk?|Who is this person?"]],
  "怎么": ["怎么 znamená jak nebo proč podle věty.", ["这个怎么说？|Zhe4ge5 zen3me5 shuo1?|Jak se to řekne?|How do you say this?", "你怎么来了？|Ni3 zen3me5 lai2 le5?|Jak to, že jsi přišel?|How come you came?", "我不知道怎么做。|Wo3 bu4 zhi1dao5 zen3me5 zuo4.|Nevím, jak to udělat.|I don't know how to do it."]],
  "现在": ["现在 znamená teď nebo v současnosti.", ["我现在在家。|Wo3 xian4zai4 zai4 jia1.|Teď jsem doma.|I am at home now.", "现在几点？|Xian4zai4 ji3 dian3?|Kolik je teď hodin?|What time is it now?", "我们现在走。|Wo3men5 xian4zai4 zou3.|Teď odcházíme.|We are leaving now."]],
  "可以": ["可以 znamená moci, smět nebo že něco je možné.", ["我可以进去吗？|Wo3 ke3yi3 jin4qu4 ma5?|Můžu jít dovnitř?|May I go in?", "这里可以坐。|Zhe4li3 ke3yi3 zuo4.|Tady se dá sedět.|You can sit here.", "你可以休息一下。|Ni3 ke3yi3 xiu1xi5 yi2 xia4.|Můžeš si chvíli odpočinout.|You can rest a little."]],
  "点": ["点 znamená bod, trochu nebo hodinu podle kontextu.", ["现在三点。|Xian4zai4 san1 dian3.|Teď jsou tři hodiny.|It is three o'clock now.", "我想喝一点水。|Wo3 xiang3 he1 yi4 dian3 shui3.|Chci se napít trochu vody.|I want to drink a little water.", "请点这里。|Qing3 dian3 zhe4li3.|Klikněte prosím sem.|Please click here."]],
  "呢": ["呢 pokračuje v tématu nebo vrací otázku zpět.", ["我很好，你呢？|Wo3 hen3 hao3, ni3 ne5?|Mám se dobře, a ty?|I am fine, and you?", "他在家呢。|Ta1 zai4 jia1 ne5.|Je doma.|He is at home.", "我的书呢？|Wo3 de5 shu1 ne5?|Kde je moje kniha?|Where is my book?"]],
  "如果": ["如果 uvádí podmínku: pokud, jestliže.", ["如果下雨，我们不去。|Ru2guo3 xia4 yu3, wo3men5 bu2 qu4.|Pokud bude pršet, nepůjdeme.|If it rains, we won't go.", "如果你有时间，请告诉我。|Ru2guo3 ni3 you3 shi2jian1, qing3 gao4su5 wo3.|Pokud máš čas, řekni mi to.|If you have time, please tell me.", "如果可以，我想休息。|Ru2guo3 ke3yi3, wo3 xiang3 xiu1xi5.|Pokud to jde, chci si odpočinout.|If possible, I want to rest."]],
  "只": ["只 znamená pouze nebo je měrové slovo pro některá zvířata a věci.", ["我只有一个问题。|Wo3 zhi3 you3 yi2 ge5 wen4ti2.|Mám jen jednu otázku.|I only have one question.", "他只喝水。|Ta1 zhi3 he1 shui3.|Pije jen vodu.|He only drinks water.", "一只猫在这里。|Yi4 zhi1 mao1 zai4 zhe4li3.|Tady je jedna kočka.|There is one cat here."]],
  "别": ["别 často znamená nedělej, ne.", ["别走。|Bie2 zou3.|Neodcházej.|Don't leave.", "别说了。|Bie2 shuo1 le5.|Už nemluv.|Stop talking.", "别担心。|Bie2 dan1xin1.|Neboj se.|Don't worry."]],
  "哦": ["哦 vyjadřuje pochopení, reakci nebo 'aha'.", ["哦，我知道了。|O4, wo3 zhi1dao5 le5.|Aha, už vím.|Oh, I understand now.", "哦，是这样。|O4, shi4 zhe4yang4.|Aha, je to tak.|Oh, that's how it is.", "哦，你来了。|O4, ni3 lai2 le5.|Aha, přišel jsi.|Oh, you came."]],
  "但": ["但 znamená ale nebo avšak, často knižněji než 但是.", ["我想去，但没时间。|Wo3 xiang3 qu4, dan4 mei2 shi2jian1.|Chci jít, ale nemám čas.|I want to go, but I don't have time.", "他很忙，但很高兴。|Ta1 hen3 mang2, dan4 hen3 gao1xing4.|Je zaneprázdněný, ale šťastný.|He is busy but happy.", "这很难，但可以做。|Zhe4 hen3 nan2, dan4 ke3yi3 zuo4.|Je to těžké, ale dá se to udělat.|This is hard, but it can be done."]],
  "被": ["被 uvádí pasivní vztah: někdo/něco bylo zasaženo dějem.", ["我的书被他拿走了。|Wo3 de5 shu1 bei4 ta1 na2 zou3 le5.|Moji knihu odnesl on.|My book was taken away by him.", "门被打开了。|Men2 bei4 da3kai1 le5.|Dveře byly otevřeny.|The door was opened.", "他被老师叫走了。|Ta1 bei4 lao3shi1 jiao4 zou3 le5.|Učitel ho zavolal pryč.|He was called away by the teacher."]],
  "走": ["走 znamená jít, odcházet nebo pohybovat se.", ["我们走吧。|Wo3men5 zou3 ba5.|Pojďme.|Let's go.", "他走了。|Ta1 zou3 le5.|Odešel.|He left.", "走路很健康。|Zou3 lu4 hen3 jian4kang1.|Chůze je zdravá.|Walking is healthy."]],
  "太": ["太 znamená příliš nebo velmi, často s 了.", ["太好了！|Tai4 hao3 le5!|Výborně!|Great!", "今天太热了。|Jin1tian1 tai4 re4 le5.|Dnes je příliš horko.|It is too hot today.", "这个太贵了。|Zhe4ge5 tai4 gui4 le5.|Tohle je moc drahé.|This is too expensive."]],
  "这样": ["这样 znamená takhle, takový nebo tímto způsobem.", ["不要这样。|Bu2 yao4 zhe4yang4.|Nedělej to takhle.|Don't do it like this.", "这样可以吗？|Zhe4yang4 ke3yi3 ma5?|Může to být takhle?|Is this okay like this?", "他就是这样的人。|Ta1 jiu4 shi4 zhe4yang4 de5 ren2.|Je to prostě takový člověk.|He is just that kind of person."]],
  "里": ["里 znamená uvnitř nebo v.", ["书在包里。|Shu1 zai4 bao1 li3.|Kniha je v tašce.|The book is in the bag.", "家里有人。|Jia1 li3 you3 ren2.|Doma někdo je.|There is someone at home.", "这里很安静。|Zhe4li3 hen3 an1jing4.|Tady je klid.|It is quiet here."]],
  "跟": ["跟 znamená s, a nebo následovat podle kontextu.", ["我跟你一起去。|Wo3 gen1 ni3 yi4qi3 qu4.|Půjdu s tebou.|I will go with you.", "他跟朋友聊天。|Ta1 gen1 peng2you5 liao2tian1.|Povídá si s kamarádem.|He chats with a friend.", "请跟我来。|Qing3 gen1 wo3 lai2.|Pojďte prosím za mnou.|Please follow me."]],
  "告诉": ["告诉 znamená říct někomu informaci.", ["请告诉我。|Qing3 gao4su5 wo3.|Řekni mi to prosím.|Please tell me.", "我告诉你一个好消息。|Wo3 gao4su5 ni3 yi2 ge5 hao3 xiao1xi5.|Řeknu ti dobrou zprávu.|I will tell you good news.", "他没有告诉我。|Ta1 mei2you3 gao4su5 wo3.|Neřekl mi to.|He did not tell me."]],
  "因为": ["因为 znamená protože a uvádí příčinu.", ["我不去，因为我累了。|Wo3 bu2 qu4, yin1wei4 wo3 lei4 le5.|Nepůjdu, protože jsem unavený/á.|I am not going because I am tired.", "因为下雨，所以我们不出门。|Yin1wei4 xia4 yu3, suo3yi3 wo3men5 bu4 chu1men2.|Protože prší, nejdeme ven.|Because it is raining, we are not going out.", "我喜欢中文，因为它很有意思。|Wo3 xi3huan5 Zhong1wen2, yin1wei4 ta1 hen3 you3 yi4si5.|Mám rád/a čínštinu, protože je zajímavá.|I like Chinese because it is interesting."]],
  "自己": ["自己 znamená sám, sama, vlastní.", ["我自己做。|Wo3 zi4ji3 zuo4.|Udělám to sám/sama.|I will do it myself.", "你要相信自己。|Ni3 yao4 xiang1xin4 zi4ji3.|Musíš věřit sám sobě.|You need to believe in yourself.", "这是我自己的书。|Zhe4 shi4 wo3 zi4ji3 de5 shu1.|To je moje vlastní kniha.|This is my own book."]],
  "再": ["再 znamená znovu nebo až potom.", ["请再说一遍。|Qing3 zai4 shuo1 yi2 bian4.|Řekněte to prosím ještě jednou.|Please say it again.", "我们明天再去。|Wo3men5 ming2tian1 zai4 qu4.|Půjdeme znovu zítra.|We will go again tomorrow.", "吃完饭再走。|Chi1 wan2 fan4 zai4 zou3.|Odejdi až po jídle.|Leave after eating."]],
  "听": ["听 znamená poslouchat nebo slyšet.", ["我听中文。|Wo3 ting1 Zhong1wen2.|Poslouchám čínštinu.|I listen to Chinese.", "你听见了吗？|Ni3 ting1jian4 le5 ma5?|Slyšel/a jsi to?|Did you hear it?", "请听我说。|Qing3 ting1 wo3 shuo1.|Prosím poslouchej, co říkám.|Please listen to me."]],
  "这里": ["这里 znamená tady nebo zde.", ["这里很好。|Zhe4li3 hen3 hao3.|Tady je to dobré.|It is good here.", "我在这里。|Wo3 zai4 zhe4li3.|Jsem tady.|I am here.", "请坐这里。|Qing3 zuo4 zhe4li3.|Sedněte si prosím sem.|Please sit here."]],
  "快": ["快 znamená rychlý, rychle nebo brzy.", ["他跑得很快。|Ta1 pao3 de5 hen3 kuai4.|Běží rychle.|He runs fast.", "快一点！|Kuai4 yi4 dian3!|Rychleji!|Faster!", "饭快好了。|Fan4 kuai4 hao3 le5.|Jídlo bude brzy hotové.|The food will be ready soon."]],
  "谁": ["谁 znamená kdo.", ["你是谁？|Ni3 shi4 shei2?|Kdo jsi?|Who are you?", "谁来了？|Shei2 lai2 le5?|Kdo přišel?|Who came?", "你在等谁？|Ni3 zai4 deng3 shei2?|Na koho čekáš?|Who are you waiting for?"]],
  "但是": ["但是 znamená ale nebo avšak.", ["我想去，但是没时间。|Wo3 xiang3 qu4, dan4shi4 mei2 shi2jian1.|Chci jít, ale nemám čas.|I want to go, but I don't have time.", "他很累，但是还在工作。|Ta1 hen3 lei4, dan4shi4 hai2 zai4 gong1zuo4.|Je unavený, ale pořád pracuje.|He is tired, but still working.", "这个很贵，但是很好。|Zhe4ge5 hen3 gui4, dan4shi4 hen3 hao3.|Je to drahé, ale dobré.|It is expensive, but good."]],
  "多": ["多 znamená mnoho, hodně nebo kolik podle otázky.", ["这里人很多。|Zhe4li3 ren2 hen3 duo1.|Je tu hodně lidí.|There are many people here.", "你多大？|Ni3 duo1 da4?|Kolik ti je let?|How old are you?", "多喝水。|Duo1 he1 shui3.|Pij víc vody.|Drink more water."]],
  "用": ["用 znamená používat nebo užívat.", ["我用手机。|Wo3 yong4 shou3ji1.|Používám telefon.|I use a phone.", "这个怎么用？|Zhe4ge5 zen3me5 yong4?|Jak se to používá?|How do you use this?", "请用中文说。|Qing3 yong4 Zhong1wen2 shuo1.|Řekněte to prosím čínsky.|Please say it in Chinese."]],
  "时候": ["时候 znamená čas, chvíle nebo období.", ["你什么时候来？|Ni3 shen2me5 shi2hou5 lai2?|Kdy přijdeš?|When will you come?", "吃饭的时候不要说话。|Chi1 fan4 de5 shi2hou5 bu2 yao4 shuo1hua4.|Při jídle nemluv.|Don't talk while eating.", "那个时候我很小。|Na4ge5 shi2hou5 wo3 hen3 xiao3.|V té době jsem byl/a malý/á.|I was young at that time."]],
  "下": ["下 znamená dolů, pod, další nebo nastoupit/sestoupit podle kontextu.", ["书在桌子下。|Shu1 zai4 zhuo1zi5 xia4.|Kniha je pod stolem.|The book is under the table.", "下个星期见。|Xia4 ge5 xing1qi1 jian4.|Uvidíme se příští týden.|See you next week.", "我要下车。|Wo3 yao4 xia4 che1.|Chci vystoupit.|I want to get off."]],
  "已经": ["已经 znamená už, již.", ["我已经吃了。|Wo3 yi3jing1 chi1 le5.|Už jsem jedl/a.|I have already eaten.", "他已经走了。|Ta1 yi3jing1 zou3 le5.|Už odešel.|He has already left.", "现在已经很晚了。|Xian4zai4 yi3jing1 hen3 wan3 le5.|Teď už je pozdě.|It is already late now."]],
  "谢谢": ["谢谢 znamená děkuji nebo děkovat.", ["谢谢你。|Xie4xie5 ni3.|Děkuji ti.|Thank you.", "谢谢你的帮助。|Xie4xie5 ni3 de5 bang1zhu4.|Děkuji za tvou pomoc.|Thank you for your help.", "不用谢谢。|Bu2 yong4 xie4xie5.|Není třeba děkovat.|No need to thank me."]],
  "为什么": ["为什么 znamená proč.", ["你为什么不去？|Ni3 wei4shen2me5 bu2 qu4?|Proč nejdeš?|Why aren't you going?", "为什么这么贵？|Wei4shen2me5 zhe4me5 gui4?|Proč je to tak drahé?|Why is it so expensive?", "我不知道为什么。|Wo3 bu4 zhi1dao5 wei4shen2me5.|Nevím proč.|I don't know why."]],
  "觉得": ["觉得 znamená myslet si nebo cítit.", ["我觉得很好。|Wo3 jue2de5 hen3 hao3.|Myslím, že je to dobré.|I think it is good.", "你觉得怎么样？|Ni3 jue2de5 zen3me5 yang4?|Co si o tom myslíš?|What do you think?", "他觉得有点累。|Ta1 jue2de5 you3 dian3 lei4.|Cítí se trochu unavený.|He feels a little tired."]],
  "天": ["天 znamená den, nebe nebo počasí podle kontextu.", ["今天天气很好。|Jin1tian1 tian1qi4 hen3 hao3.|Dnes je pěkné počasí.|The weather is good today.", "一天很短。|Yi4 tian1 hen3 duan3.|Jeden den je krátký.|One day is short.", "天黑了。|Tian1 hei1 le5.|Setmělo se.|It got dark."]],
  "像": ["像 znamená podobat se, vypadat jako nebo jako.", ["他像老师。|Ta1 xiang4 lao3shi1.|Vypadá jako učitel.|He looks like a teacher.", "这个像苹果。|Zhe4ge5 xiang4 ping2guo3.|Tohle vypadá jako jablko.|This looks like an apple.", "你说得像中国人。|Ni3 shuo1 de5 xiang4 Zhong1guo2 ren2.|Mluvíš jako Číňan.|You speak like a Chinese person."]],
  "这么": ["这么 znamená tak, takhle nebo tolik.", ["你怎么这么快？|Ni3 zen3me5 zhe4me5 kuai4?|Jak to, že jsi tak rychlý/á?|How are you so fast?", "这个这么好吃。|Zhe4ge5 zhe4me5 hao3chi1.|Tohle je tak dobré.|This tastes so good.", "不要这么说。|Bu2 yao4 zhe4me5 shuo1.|Neříkej to takhle.|Don't say it like this."]],
  "它": ["它 znamená ono nebo to pro věci a zvířata.", ["它很好吃。|Ta1 hen3 hao3chi1.|Je to moc dobré k jídlu.|It tastes very good.", "我喜欢它。|Wo3 xi3huan5 ta1.|Mám to rád/a.|I like it.", "它在桌子上。|Ta1 zai4 zhuo1zi5 shang4.|Je to na stole.|It is on the table."]],
  "从": ["从 znamená od, z nebo skrz.", ["我从家来。|Wo3 cong2 jia1 lai2.|Přicházím z domu.|I come from home.", "从这里走。|Cong2 zhe4li3 zou3.|Jdi odsud.|Go from here.", "他从早到晚工作。|Ta1 cong2 zao3 dao4 wan3 gong1zuo4.|Pracuje od rána do večera.|He works from morning to evening."]],
  "先生": ["先生 znamená pan, učitel nebo zdvořilé oslovení muže.", ["王先生在吗？|Wang2 xian1sheng5 zai4 ma5?|Je pan Wang tady?|Is Mr. Wang here?", "先生，请坐。|Xian1sheng5, qing3 zuo4.|Pane, posaďte se prosím.|Sir, please sit down.", "他是一位先生。|Ta1 shi4 yi2 wei4 xian1sheng5.|Je to gentleman.|He is a gentleman."]],
  "找": ["找 znamená hledat nebo snažit se najít.", ["我找你。|Wo3 zhao3 ni3.|Hledám tě.|I am looking for you.", "你在找什么？|Ni3 zai4 zhao3 shen2me5?|Co hledáš?|What are you looking for?", "我找不到手机。|Wo3 zhao3 bu2 dao4 shou3ji1.|Nemůžu najít telefon.|I can't find my phone."]],
  "最": ["最 tvoří superlativ: nejvíc, nej-.", ["这个最好。|Zhe4ge5 zui4 hao3.|Tohle je nejlepší.|This is the best.", "我最喜欢中文。|Wo3 zui4 xi3huan5 Zhong1wen2.|Nejvíc mám rád/a čínštinu.|I like Chinese the most.", "今天最冷。|Jin1tian1 zui4 leng3.|Dnes je nejchladněji.|Today is the coldest."]],
  "喜欢": ["喜欢 znamená mít rád nebo líbit se.", ["我喜欢中文。|Wo3 xi3huan5 Zhong1wen2.|Mám rád/a čínštinu.|I like Chinese.", "你喜欢喝茶吗？|Ni3 xi3huan5 he1 cha2 ma5?|Máš rád/a čaj?|Do you like drinking tea?", "他不喜欢太热的天。|Ta1 bu4 xi3huan5 tai4 re4 de5 tian1.|Nemá rád moc horké dny.|He does not like very hot days."]],
  "可": ["可 může znamenat moci, smět nebo zdůraznit pocit.", ["这可不是小事。|Zhe4 ke3 bu2 shi4 xiao3 shi4.|To opravdu není maličkost.|This is really not a small matter.", "可不可以进去？|Ke3 bu4 ke3yi3 jin4qu4?|Dá se jít dovnitř?|Can we go in?", "他可高兴了。|Ta1 ke3 gao1xing4 le5.|Byl opravdu šťastný.|He was really happy."]],
  "为": ["为 znamená pro, kvůli nebo jako součást slovesných vazeb.", ["我为你高兴。|Wo3 wei4 ni3 gao1xing4.|Mám z tebe radost.|I am happy for you.", "他为了学习中文，每天听。|Ta1 wei4le5 xue2xi2 Zhong1wen2, mei3tian1 ting1.|Kvůli studiu čínštiny poslouchá každý den.|To study Chinese, he listens every day.", "这本书为学生写的。|Zhe4 ben3 shu1 wei4 xue2sheng5 xie3 de5.|Tahle kniha je napsaná pro studenty.|This book is written for students."]],
  "大": ["大 znamená velký, hlavní nebo dospělý podle kontextu.", ["这个房间很大。|Zhe4ge5 fang2jian1 hen3 da4.|Tenhle pokoj je velký.|This room is big.", "他比我大。|Ta1 bi3 wo3 da4.|Je starší než já.|He is older than me.", "今天风很大。|Jin1tian1 feng1 hen3 da4.|Dnes fouká silný vítr.|The wind is strong today."]],
  "可能": ["可能 znamená možná nebo je možné.", ["他可能不来。|Ta1 ke3neng2 bu4 lai2.|Možná nepřijde.|He may not come.", "这可能是真的。|Zhe4 ke3neng2 shi4 zhen1 de5.|To může být pravda.|This may be true.", "明天可能下雨。|Ming2tian1 ke3neng2 xia4 yu3.|Zítra možná bude pršet.|It may rain tomorrow."]]
};

const breakdownPieces = {
  "为什么": "为什么 = proč / why",
  "什么": "什么 = co / what",
  "我们": "我们 = my / we",
  "你们": "你们 = vy / you plural",
  "他们": "他们 = oni / they",
  "没有": "没有 = nemít, není / not have, there is not",
  "知道": "知道 = vědět / to know",
  "可以": "可以 = moci, smět / can, may",
  "如果": "如果 = pokud / if",
  "因为": "因为 = protože / because",
  "但是": "但是 = ale / but",
  "自己": "自己 = sám, vlastní / self, own",
  "这里": "这里 = tady / here",
  "现在": "现在 = teď / now",
  "已经": "已经 = už / already",
  "喜欢": "喜欢 = mít rád / to like",
  "可能": "可能 = možná, možný / maybe, possible",
  "先生": "先生 = pan, gentleman / mister, gentleman",
  "告诉": "告诉 = říct někomu / to tell",
  "觉得": "觉得 = myslet si, cítit / to think, to feel",
  "时候": "时候 = čas, chvíle / time, moment",
  "这个": "这个 = tento, tohle / this one",
  "这样": "这样 = takhle / like this",
  "这么": "这么 = tak, tolik / so, this much",
  "一个": "一个 = jeden, nějaký / one, a",
  "一点": "一点 = trochu / a little",
  "一起": "一起 = spolu / together",
  "一下": "一下 = na chvilku / a little moment",
  "中文": "中文 = čínština / Chinese language",
  "中国": "中国 = Čína / China",
  "学生": "学生 = student / student",
  "老师": "老师 = učitel / teacher",
  "朋友": "朋友 = kamarád / friend",
  "问题": "问题 = otázka, problém / question, problem",
  "时间": "时间 = čas / time",
  "今天": "今天 = dnes / today",
  "明天": "明天 = zítra / tomorrow",
  "昨天": "昨天 = včera / yesterday",
  "下雨": "下雨 = pršet / to rain",
  "出门": "出门 = jít ven / to go out",
  "工作": "工作 = pracovat / to work",
  "学习": "学习 = učit se / to study",
  "说话": "说话 = mluvit / to talk",
  "喝水": "喝水 = pít vodu / to drink water",
  "看书": "看书 = číst knihu / to read a book",
  "做饭": "做饭 = vařit / to cook",
  "休息": "休息 = odpočívat / to rest",
  "高兴": "高兴 = šťastný, mít radost / happy",
  "重要": "重要 = důležitý / important",
  "好吃": "好吃 = chutný / tasty",
  "有意思": "有意思 = zajímavý / interesting",
  "没时间": "没时间 = nemít čas / have no time",
  "不知道": "不知道 = nevědět / do not know",
  "不去": "不去 = nejít / not go",
  "累了": "累了 = unavil/a se / became tired",
  "走了": "走了 = odešel / left",
  "来了": "来了 = přišel / came",
  "吃了": "吃了 = jedl/a, dokončený děj / ate, completed action",
  "我的": "我的 = moje / my, mine",
  "你的": "你的 = tvoje / your, yours",
  "他的": "他的 = jeho / his",
  "她的": "她的 = její / her",
  "书": "书 = kniha / book",
  "水": "水 = voda / water",
  "家": "家 = domov / home",
  "人": "人 = člověk / person",
  "钱": "钱 = peníze / money",
  "门": "门 = dveře / door",
  "灯": "灯 = světlo, lampa / light, lamp",
  "车": "车 = auto, vozidlo / car, vehicle",
  "猫": "猫 = kočka / cat",
  "苹果": "苹果 = jablko / apple",
  "桌子": "桌子 = stůl / table",
  "手机": "手机 = telefon / phone",
  "电影": "电影 = film / movie",
  "名字": "名字 = jméno / name",
  "天气": "天气 = počasí / weather",
  "我": "我 = já / I",
  "你": "你 = ty / you",
  "他": "他 = on / he",
  "她": "她 = ona / she",
  "它": "它 = ono, to / it",
  "是": "是 = být / to be",
  "了": "了 = částice změny nebo dokončení / change or completion particle",
  "不": "不 = ne, zápor / not",
  "在": "在 = být v/na, probíhající děj / at, in, ongoing action",
  "有": "有 = mít, existovat / to have, there is",
  "这": "这 = toto / this",
  "那": "那 = tamto, ten / that",
  "就": "就 = hned, právě, tedy / just, then",
  "会": "会 = umět, bude / can, will",
  "吗": "吗 = otázková částice / question particle",
  "要": "要 = chtít, muset / want, need to",
  "说": "说 = říct, mluvit / say, speak",
  "请": "请 = prosím / please",
  "慢慢": "慢慢 = pomalu / slowly",
  "想": "想 = chtít, myslet / want, think",
  "一": "一 = jeden / one",
  "很": "很 = velmi / very",
  "吧": "吧 = částice návrhu nebo změkčení / suggestion-softening particle",
  "来": "来 = přijít / come",
  "都": "都 = všichni, všechno / all",
  "个": "个 = obecné měrové slovo / general measure word",
  "能": "能 = moci / can",
  "去": "去 = jít / go",
  "没": "没 = zápor pro mít nebo minulý děj / negative for have or past action",
  "和": "和 = a, s / and, with",
  "到": "到 = dorazit, do / arrive, to",
  "对": "对 = správný, vůči / correct, toward",
  "也": "也 = také / also",
  "啊": "啊 = citoslovce nebo větná částice / interjection or modal particle",
  "还": "还 = ještě, také / still, also",
  "把": "把 = částice pro předmět před slovesem / ba object marker",
  "让": "让 = nechat, dovolit / let, allow",
  "做": "做 = dělat / do, make",
  "给": "给 = dát, pro / give, for",
  "上": "上 = nahoře, na / on, above",
  "过": "过 = zkušenostní částice, projít / experience marker, pass",
  "得": "得 = částice způsobu, muset / manner particle, must",
  "看": "看 = dívat se, číst / look, read",
  "真": "真 = opravdu / really",
  "着": "着 = částice trvajícího stavu / durative state particle",
  "亮": "亮 = svítit, jasný / bright, lit",
  "事": "事 = věc, záležitost / matter",
  "怎么": "怎么 = jak, proč / how, why",
  "点": "点 = bod, trochu, hodina / point, a little, o'clock",
  "呢": "呢 = částice tématu nebo otázky / topic or question particle",
  "只": "只 = jen, měrové slovo / only, classifier",
  "别": "别 = nedělej / do not",
  "担心": "担心 = bát se, dělat si starosti / worry",
  "哦": "哦 = aha, ó / oh",
  "但": "但 = ale / but",
  "被": "被 = pasivní částice / passive marker",
  "走": "走 = jít, odejít / walk, leave",
  "坐": "坐 = sedět, sednout si / sit",
  "太": "太 = příliš, velmi / too, very",
  "里": "里 = uvnitř / inside",
  "跟": "跟 = s, následovat / with, follow",
  "再": "再 = znovu, potom / again, then",
  "听": "听 = poslouchat, slyšet / listen, hear",
  "快": "快 = rychlý, brzy / fast, soon",
  "谁": "谁 = kdo / who",
  "多": "多 = mnoho, hodně / many, much",
  "用": "用 = používat / use",
  "下": "下 = dole, pod, příští / down, below, next",
  "谢谢": "谢谢 = děkuji / thank you",
  "天": "天 = den, nebe / day, sky",
  "像": "像 = podobat se / resemble, like",
  "从": "从 = od, z / from",
  "找": "找 = hledat / look for",
  "最": "最 = nejvíc, nej- / most",
  "可": "可 = moci, smět, zdůraznění / can, may, emphasis",
  "为": "为 = pro, kvůli / for, because of",
  "大": "大 = velký / big"
};

function buildExampleBreakdown(sentence, word, cz, en) {
  const pieces = [];
  const seen = new Set();

  function add(piece) {
    if (!piece || seen.has(piece)) {
      return;
    }
    seen.add(piece);
    pieces.push(piece);
  }

  if (sentence.includes(word)) {
    add(word + " = " + cz + " / " + en);
  }

  Object.keys(breakdownPieces)
    .sort(function(a, b) {
      return b.length - a.length;
    })
    .forEach(function(key) {
      if (pieces.length >= 7 || key === word) {
        return;
      }

      if (sentence.includes(key)) {
        add(breakdownPieces[key]);
      }
    });

  return pieces.length ? pieces : [word + " = " + cz + " / " + en];
}

function makeWordExample(parts, word, cz, en) {
  return {
    zh: parts[0],
    py: parts[1],
    cs: parts[2],
    en: parts[3],
    breakdown: buildExampleBreakdown(parts[0], word, cz, en)
  };
}

window.frequencyWords = window.frequencyWords.map(function(entry) {
  const detail = usageData[entry.word];

  if (!detail) {
    return entry;
  }

  return Object.assign({}, entry, {
    explanation: detail[0],
    examples: detail[1].map(function(line) {
      return makeWordExample(line.split("|"), entry.word, entry.cz, entry.en);
    })
  });
});
